In [1]:
import pandas as pd
from pandas import pivot_table

In [4]:
data = pd.read_csv("dataset.csv")

In [6]:
data.head()

   ID  OrderID      Client     Sum Currency        Date Category  ServiceType
0   1  10293.0   Client_17  992575      RUR  2026-04-22       КЗ          2.0
1   2  10296.0  Client_141  365546      RUR  2025-10-22       ДЗ          4.0
2   3  10243.0  Client_139  655622      USD  2026-11-25       КЗ          7.0
3   4  10125.0   Client_75  952346      RUR  2026-07-14       КЗ          7.0
4   5  10243.0   Client_77   19775      USD  2025-06-11       КЗ          7.0

In [12]:
data.groupby(by=["Category", "ServiceType"])["Sum"].mean()

Category  ServiceType
ДЗ        1.0            531860.555556
          2.0            498697.485714
          3.0            558527.617021
          4.0            433744.418605
          5.0            471645.500000
          6.0            494972.150685
          7.0            538125.500000
КЗ        1.0            471230.133333
          2.0            476515.000000
          3.0            456928.036364
          4.0            507794.555556
          5.0            489339.906250
          6.0            507314.318182
          7.0            527102.223881
Name: Sum, dtype: float64

In [13]:
data.pivot_table(values="Sum", index="ServiceType",columns="Category", aggfunc='mean')

Category                ДЗ             КЗ
ServiceType
1.0          531860.555556  471230.133333
2.0          498697.485714  476515.000000
3.0          558527.617021  456928.036364
4.0          433744.418605  507794.555556
5.0          471645.500000  489339.906250
6.0          494972.150685  507314.318182
7.0          538125.500000  527102.223881